//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 12:49:25 PM EDT 
//


package us.jonesrychtar.gispatialnet.Reader.kml.opengis;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ScaleScalar
    extends JAXBElement<Double>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "scale");

    public ScaleScalar(Double value) {
        super(NAME, ((Class) Double.class), null, value);
    }

    public ScaleScalar() {
        super(NAME, ((Class) Double.class), null, null);
    }

}
